{
 "title": "Loki",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "log_type",
    "label": "log_type",
    "query": "label_values({log_type=~\".+\"}, log_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Count of Logs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({log_type=~\"$log_type\"})[15m]))"
    }
   ]
  },
  {
   "title": "Total Count of Error ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=~\".+\"} |= \"error\" [15m]))"
    }
   ]
  },
  {
   "title": "Total Count of Unknown",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=~\"$log_type\"} |= \"unknown\" [15m]))"
    }
   ]
  },
  {
   "title": "Audit Log by Verb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=\"audit\"} | json | verb=~\".+\" [15m])) by (verb)",
     "legendFormat": "{{ verb }}"
    }
   ]
  },
  {
   "title": "Total Count of Info ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=~\"$log_type\"} |= \"info\" [15m]))"
    }
   ]
  },
  {
   "title": "Total Count of Warn",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=~\".+\"} |= \"warn\" [15m]))"
    }
   ]
  },
  {
   "title": "Total Count by Log Type",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(count_over_time({log_type=~\"$log_type\"}[15m])) by (log_type)",
     "legendFormat": "{{ log_type }}"
    }
   ]
  },
  {
   "title": "Erros by Pod",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time({log_type=~\"$log_type\"} |= \"error\" [15m])) by (kubernetes_pod_name))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Erros by Namespace ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5,sum(count_over_time({log_type=~\"$log_type\"} |= \"error\" [15m])) by (kubernetes_namespace_name))",
     "legendFormat": "{{ kubernetes_namespace_name }}"
    }
   ]
  },
  {
   "title": "Live Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{log_type=~\"$log_type\"}"
    }
   ]
  }
 ]
}