{
 "title": "AAP - Metrics",
 "tags": [
  "Node_Exporter",
  "Prometheus",
  "Ansible",
  "AAP",
  "Red Hat"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Exporter",
    "query": {
     "query": "label_values(node_uname_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "AAP Instance",
    "query": {
     "query": "label_values(awx_system_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "License and Configuration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 1, "y": 1 },
   "options": {
    "content": "<!-- <img src=\"https://www.ansible.com/hubfs/Logo-Red_Hat-Ansible_Automation_Platform-A-Standard.svg\"> -->\n<img src=\"https://www.redhat.com/cms/managed-files/ansible-logo_0_0.png\" width=\"200px\" height=\"200px\">\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_instance_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "License Type",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Insights ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hosts Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_license_instance_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Hosts Available",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_license_instance_free{instance=~\"$instance\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Hosts Used",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ( awx_license_instance_free{instance=~\"$instance\"} / awx_license_instance_total{instance=~\"$instance\"} * 100 )",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(awx_instance_info{instance=~\"$instance\",hostname=~\".*\"})"
    }
   ]
  },
  {
   "title": "License Expiry",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "External Logger",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_system_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Access",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(awx_users_total{instance=~\"$instance\"})",
     "legendFormat": "Users"
    },
    {
     "expr": "sum(awx_teams_total{instance=~\"$instance\"})",
     "legendFormat": "Teams"
    },
    {
     "expr": "sum(awx_organizations_total{instance=~\"$instance\"})",
     "legendFormat": "Organizations"
    },
    {
     "expr": "sum(awx_sessions_total{instance=~\"$instance\",type=\"all\"})",
     "legendFormat": "Online Users"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 10, "x": 7, "y": 8 },
   "targets": [
    {
     "expr": "sum(awx_inventories_total{instance=~\"$instance\"})",
     "legendFormat": "Inventory"
    },
    {
     "expr": "sum(awx_projects_total{instance=~\"$instance\"})",
     "legendFormat": "Projects"
    },
    {
     "expr": "sum(awx_job_templates_total{instance=~\"$instance\"})",
     "legendFormat": "Job Template"
    },
    {
     "expr": "sum(awx_workflow_job_templates_total{instance=~\"$instance\"})",
     "legendFormat": "Workflow"
    },
    {
     "expr": "sum(awx_hosts_total{instance=~\"$instance\",type=\"active\"})",
     "legendFormat": "Active Hosts"
    },
    {
     "expr": "sum(awx_schedules_total{instance=~\"$instance\"})",
     "legendFormat": "Schedules"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "awx_instance_cpu{instance=~\"$instance\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "awx_instance_memory{instance=~\"$instance\"}",
     "legendFormat": "Memory"
    },
    {
     "expr": "awx_instance_capacity{instance=~\"$instance\"}",
     "legendFormat": "Forks"
    }
   ]
  },
  { "title": "Ansible Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Job Launched Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"error\"})",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"canceled\"})",
     "legendFormat": "Canceled"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"successful\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"waiting\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"pending\"})",
     "legendFormat": "Pending"
    }
   ]
  },
  {
   "title": "Job Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(awx_status_total{instance=~\"$instance\",status=\"successful\"})",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(sum(awx_status_total{instance=~\"$instance\",status=\"failed\"}) + sum(awx_status_total{instance=~\"$instance\",status=\"error\"}))",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Time Execution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(task_manager_get_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Loading Tasks"
    },
    {
     "expr": "avg(irate(task_manager_start_task_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Starting Tasks"
    },
    {
     "expr": "avg(irate(task_manager_process_running_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Processing Running Tasks"
    },
    {
     "expr": "avg(irate(task_manager_process_pending_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Processing Pending Tasks"
    }
   ]
  },
  {
   "title": "Transactions Time  - Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(irate(task_manager_commit_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "DB Transactions"
    },
    {
     "expr": "avg(irate(dependency_manager_get_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Loading Pending Tasks from DB"
    },
    {
     "expr": "avg(irate(workflow_manager_get_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Loading Workflow Tasks from DB"
    },
    {
     "expr": "avg(irate(callback_receiver_events_insert_db_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Saving Events to DB"
    },
    {
     "expr": "avg(irate(task_manager_get_tasks_seconds{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "Loading Tasks from DB"
    }
   ]
  },
  {
   "title": "Hardware Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "IoWait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\",  mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "Other"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{job=\"$job\"}) by (cpu)))",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"} - node_memory_MemFree_bytes{job=\"$job\"} - (node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_SReclaimable_bytes{job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"$job\"} + node_memory_Buffers_bytes{job=\"$job\"} + node_memory_SReclaimable_bytes{job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=\"$job\"} - node_memory_SwapFree_bytes{job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - Transmit"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$job\",device!~'rootfs'} * 100) / node_filesystem_size_bytes{job=\"$job\",device!~'rootfs'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  }
 ]
}